### ISSUE TITLE
Do we have AzureOpenAI Implentation and other models too?

### ISSUE THREAD

**Issue by wanjeakshay** [TAG-Research/lotus#20]
I want to do the retrieval process using AzureOpen AI model, how to do it, where can i pass those extra variables?

**Comment by liana313** [comment]
PR #26 (merged today) adds support for a wide variety of model endpoints, including Azure OpenAI. You would need to export your api key and specify the model (eg "azure/gpt4-o1-mini") when initializing the LM. Here's an example https://github.com/TAG-Research/lotus/blob/main/examples/op_examples/agg.py
