### ISSUE TITLE
Compatibility Issue with Python 3 and PEP 517 Build Error in lotus-core 0.0.6

### ISSUE THREAD

**Issue by nickchen1998** [TAG-Research/lotus#7]
Dear Maintainers,

I encountered an issue while trying to install `lotus-core` version 0.0.6 using Poetry. The installation failed due to a syntax error related to Python 2-style `print` statements, as well as an issue with PEP 517 build compatibility.

Here is the error message I received:

```
ChefBuildError

Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  File "<string>", line 31
    print "===== compile python4lotus ====="
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("===== compile python4lotus =====")?
```

It seems that the code is using Python 2 syntax, which causes a failure when using Python 3. Additionally, the error message suggests that `lotus-core` does not fully support PEP 517 builds, which may be contributing to the issue.

**Steps to Reproduce:**
1. Run `poetry add lotus` in a Python 3 environment.
2. Observe the installation failure due to the above error.

**Environment:**
- Poetry version: 1.8.2
- Python version: 3.9
- `lotus-core` version: 0.0.6

I would appreciate it if you could take a look into this issue. If there's anything I can do to assist in resolving this or further steps I should try, please let me know.

Thank you for your time and for maintaining this project!

Best regards,  
Nick Chen

**Comment by liana313** [comment]
Hi Nick, can you double check that you're installing the right package (it should be lotus-ai - https://pypi.org/project/lotus-ai/). There are some similarly-named packages, which may be causing the error

**Comment by nickchen1998** [comment]
Ah, it turns out I got the package name wrong. I’ve successfully downloaded the correct package and ran the code. Thank you very much!
